### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by naomicaselli** [ASL-LEX/SignLab#62]
**Describe the bug**
When I set up a new project, it didn't get added to the Environment > Project tab until I reloaded the page 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ventura 13.2 (22D49)
 - Browser Chrome
 - Version Version 110.0.5481.77

**Comment by cbolles** [comment]
Found that neither projects nor studies automatically updated, so adjusted accordingly. Fix will be present in the next release.
