### ISSUE TITLE
Construct Tagging Interface- dataset name

### ISSUE THREAD

**Issue by naomicaselli** [ASL-LEX/SignLab#64]
**Describe the bug**
The dataset name changed to some kind of code, rather than the English dataset name when I clicked on Minimum Required

**Screenshots**

<img width="632" alt="screenshot" src="https://user-images.githubusercontent.com/9668665/219481905-e222ce9f-0f56-41f9-8ef9-2a104390b6e6.png">

**Comment by cbolles** [comment]
Found the source of the issue. Should be resolved when the next release is published.
