### ISSUE TITLE
Screen position

### ISSUE THREAD

**Issue by naomicaselli** [ASL-LEX/SignLab#69]
**Describe the bug**
The text boxes for doing the study overlap with the video.

**Screenshots**
<img width="1142" alt="Screenshot 2023-02-24 at 1 51 21 PM" src="https://user-images.githubusercontent.com/9668665/221266822-e50a2eb2-4542-4d9d-94f0-b726b698f6d9.png">

**Comment by cbolles** [comment]
Fixed the issue so the field won't overlap anymore. If the screen gets too small it will at worst allow for scrolling. Fix will be present in the next release
