### ISSUE TITLE
search result rankings

### ISSUE THREAD

**Issue by naomicaselli** [ASL-LEX/SignLab#72]
**Describe the bug**
When I search for a sign, the top ranked choices are a bit unexpected. Here the sign "understand" is several items down. Also, the videos aren't loading (maybe I need to change the vimeo settings?)

It would be great to have a 1:1 gloss match be the highest ranked option (i.e., search the EntryIDs first, then search the SignBank English translations). 

<img width="1016" alt="Screenshot 2023-03-04 at 3 36 13 PM" src="https://user-images.githubusercontent.com/9668665/222937742-d3d7f3b5-80b7-4fbd-8aa8-9fbb3f523d21.png">

**Comment by cbolles** [comment]
The current order is based on what Knack provides. Once we have the dedicated ASL-LEX hosting service we can specify the order. The order right now certainly is not helpful and hinders speed when it comes to tagging.

For having the videos load, it may be a Vimeo setting, Vimeo has been a little difficult so we may also want to host the videos ourselves for the custom ASL-LEX hosting. However in Vimeo (this is guess work on my side) you may be able to add allowed hosts which can embed the videos in which case adding `signlab.sail.codes` may resolve the issue.

**Comment by BUlexlab** [comment]
Ah right, that makes sense.
