### ISSUE TITLE
Dataset permissions

### ISSUE THREAD

**Issue by BUlexlab** [ASL-LEX/SignLab#76]
**Describe the bug**
I gave a user access to a dataset, clicked away, and then their access toggled back to "no". 

https://user-images.githubusercontent.com/43891422/225703421-310f41b7-0706-4ccf-9997-4d00edebbdea.mov

**Comment by cbolles** [comment]
Is this a recurring problem if you refresh your webpage? If so, could you be able to capture the output to your console when the issue takes place? Thank you!

**Comment by cbolles** [comment]
@BUlexlab I found the source of the problem, the issue was that the UI was not updating, however the permission was indeed changing. I put in a fix that makes sure the UI reflects the permissions correctly.
